package com.epimorphics.vocabs;
/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from src/main/webapp/vocabs/internal.ttl 
 * @author Auto-generated by schemagen on 20 Dec 2010 21:45 
 */
public class Internal {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.epimorphics.com/vocabularies/spend/internal#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>links to an externally attached freetext annotation</p> */
    public static final Property annotation = m_model.createProperty( "http://www.epimorphics.com/vocabularies/spend/internal#annotation" );
    
    /** <p>unique identifier for entity, usable as a 'slug' in a composite URI</p> */
    public static final Property identifier = m_model.createProperty( "http://www.epimorphics.com/vocabularies/spend/internal#identifier" );
    
    /** <p>links a supplier to a councils they have supplied</p> */
    public static final Property supplies = m_model.createProperty( "http://www.epimorphics.com/vocabularies/spend/internal#supplies" );
    
    /** <p>the free text comment making up this annotation</p> */
    public static final Property text = m_model.createProperty( "http://www.epimorphics.com/vocabularies/spend/internal#text" );
    
    /** <p>A form of cube slice which includes aggregates of the (implicit) contained 
     *  observation</p>
     */
    public static final Resource AggregationSlice = m_model.createResource( "http://www.epimorphics.com/vocabularies/spend/internal#AggregationSlice" );
    
    /** <p>an externally attached freetext annotation</p> */
    public static final Resource Annotation = m_model.createResource( "http://www.epimorphics.com/vocabularies/spend/internal#Annotation" );
    
    /** <p>something that acts as a payee in the data</p> */
    public static final Resource Supplier = m_model.createResource( "http://www.epimorphics.com/vocabularies/spend/internal#Supplier" );
    
}
