package com.epimorphics.vocabs;
/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from src/main/vocabs/record.ttl 
 * @author Auto-generated by schemagen on 11 Dec 2011 22:10 
 */
public class Record {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://data.epimorphics.com/def/record#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>denotes who can read the collection</p> */
    public static final Property accessibleBy = m_model.createProperty( "http://data.epimorphics.com/def/record#accessibleBy" );
    
    /** <p>a classification for the record/collection</p> */
    public static final Property category = m_model.createProperty( "http://data.epimorphics.com/def/record#category" );
    
    /** <p>a description of the entity described by this metadata record</p> */
    public static final Property description = m_model.createProperty( "http://data.epimorphics.com/def/record#description" );
    
    /** <p>denotes the metadata record for an entity</p> */
    public static final Property hasRecord = m_model.createProperty( "http://data.epimorphics.com/def/record#hasRecord" );
    
    /** <p>denotes the collection which contains the metadata record</p> */
    public static final Property inCollection = m_model.createProperty( "http://data.epimorphics.com/def/record#inCollection" );
    
    /** <p>the label of the entity described by this metadata record</p> */
    public static final Property label = m_model.createProperty( "http://data.epimorphics.com/def/record#label" );
    
    /** <p>denotes who can change or delete the collection</p> */
    public static final Property modifiableBy = m_model.createProperty( "http://data.epimorphics.com/def/record#modifiableBy" );
    
    /** <p>the status of the entity described by the record</p> */
    public static final Property status = m_model.createProperty( "http://data.epimorphics.com/def/record#status" );
    
    /** <p>Represents a metadata record for a collection of records in the registry</p> */
    public static final Resource Collection = m_model.createResource( "http://data.epimorphics.com/def/record#Collection" );
    
    /** <p>Represents a metadata record for some resource in the registry</p> */
    public static final Resource Record = m_model.createResource( "http://data.epimorphics.com/def/record#Record" );
    
    /** <p>A user role, used for access control purposes</p> */
    public static final Resource Role = m_model.createResource( "http://data.epimorphics.com/def/record#Role" );
    
    /** <p>Represents the status which which the corresponding entity is regarded by 
     *  the registry owner</p>
     */
    public static final Resource Status = m_model.createResource( "http://data.epimorphics.com/def/record#Status" );
    
    public static final Resource anon = m_model.createResource( "http://data.epimorphics.com/def/record#anon" );
    
}
